var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/core-business-1/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__bd7c30d9._.js")
R.c("server/chunks/ssr/_9411e916._.js")
R.c("server/chunks/ssr/_3d239c73._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__74fbfb61._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_f9713a08._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__fb6dea2c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_core-business-1_page_actions_aceb5d7a.js")
R.m(28567)
module.exports=R.m(28567).exports
